name: Build & Release

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux ]
        arch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with: { go-version: '1.24' }
      - name: Build ${{ matrix.arch }}
        run: |
          mkdir -p artifacts
          GOOS=linux GOARCH=${{ matrix.arch }} \
            go build -ldflags="-s -w" \
            -o artifacts/mkxray-${{ matrix.arch }} .
      - uses: actions/upload-artifact@v4
        with:
          name: mkxray-${{ matrix.arch }}
          path: artifacts/mkxray-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: build
      - name: Create GitHub Release and upload binaries
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          artifacts: build/*
