name: Build & Release

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build ${{ matrix.os }} / ${{ matrix.arch }}
        run: |
          mkdir -p build
          ext=""
          if [ "${{ matrix.os }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
            go build -ldflags="-s -w" \
            -o build/myprog-${{ matrix.os }}-${{ matrix.arch }}${ext} \
            .

      - name: Run Tests
        run: |
          go test ./... -v
